# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter test

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  test-flutter-app:
    # You may pin to the exact commit or the version.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: 3.10.0
          channel: stable
          cache: true
      - run: flutter clean
      - run: flutter pub get
