name: Firebase Flutter Secrets
run-name: ${{ github.action }} on Check Secrets

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-with-firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: 3.10.0
          channel: stable
          cache: true

      - name: Set up Firebase Config
        run: |
          sudo echo $FIREBASE_APP_ID_FILE | base64 --decode > ios/firebase_app_id_file.json
          sudo echo $FIREBASE_OPTIONS | base64 --decode > lib/firebase_options.dart
          sudo echo $GOOGLESERVICE_INFO | base64 --decode > ios/Runner/GoogleService-Info.plist
          sudo echo $GOOGLE_SERVICES | base64 --decode > android/app/google-services.json
        env:
          FIREBASE_APP_ID_FILE: ${{ secrets.FIREBASE_APP_ID_FILE }}
          FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS }}
          GOOGLESERVICE_INFO: ${{ secrets.GOOGLESERVICE_INFO }}
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}

      - name: clean and get
        run: |
          flutter clean
          flutter pub get
      - name: build APK
        run: flutter build
