name: Firebase Flutter Secrets
run-name: ${{ github.actor }} is Check Secrets
on:
  push:
    branches: [main, dev]

jobs:
  build-with-firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: 3.10.0
          channel: stable
          cache: true

      - name: Set up Firebase Config
        run: |
          echo "$FIREBASE_APP_ID_FILE" > ios/firebase_app_id_file.json
          echo "$FIREBASE_OPTIONS" > lib/firebase_options.dart
          echo "$GOOGLESERVICE_INFO" > ios/Runner/GoogleService-Info.plist
          echo "$GOOGLE_SERVICES" > android/app/google-services.json
        env:
          FIREBASE_APP_ID_FILE: ${{secrets.FIREBASE_APP_ID_FILE}}
          FIREBASE_OPTIONS: ${{secrets.FIREBASE_OPTIONS}}
          GOOGLESERVICE_INFO: ${{secrets.GOOGLESERVICE_INFO}}
          GOOGLE_SERVICES: ${{secrets.GOOGLE_SERVICES}}

      - name: Build and Test
        run: |
          flutter pub get
          flutter build apk --release
